//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoeduSam
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSales
    {
        public int id { get; set; }
        public int ProductId { get; set; }
        public int Kolichestvo { get; set; }
        public System.DateTime DateSale { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
